version: "3.2"

services:
  database:
    image: mysql:8.0.21
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_RANDOM_ROOT_PASSWORD: 'no'
  company:
    build: ./backend/core/services/company
    ports:
      - "13070:13070"