service:
  port: "13080"
  logLevel: 4 # 1 - CRITICAL, 2 - WARNING, 3 - INFO, 4 - DEBUG
company:
  url: "http://company:13070/api"
cabinet:
  url: "http://cabinet:13060/api"
schedule:
  url: "http://schedule:13050/api"